### ISSUE TITLE
setTimeout is handled specially in node 8, but not util-promisify

### ISSUE THREAD

**Issue by mhirsch** [juliangruber/util-promisify#1]
The node docs say that there is a promiseified version of `setTimeout()` that's available through `util.promisify`: https://nodejs.org/api/timers.html

However:

```
var promisify = require('util-promisify');
var delay = promisify(setTimeout);
delay(1000).then(() => console.log("done") ).catch( console.error );
```
results in
```
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:348:11)
    at ../node_modules/util-promisify/index.js:45:12
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
```
Since the default version of `setTimeout` has a funny calling convention.

This is using node v.6.10, which doesn't have `util.promisify`.

Thanks for making this, by the way!

**Comment by juliangruber** [comment]
thanks for reporting! :) 2.1.0
